version: 2.1


workflows:
  plan-and-deploy:
    jobs:
      - tf:

jobs:
  tf:
    working_directory: ~/repo/terraform
    docker:
      - image: jl98/default:v1.0.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Debug
          command: |
            ls -la
            pwd
      - run:
          name: Az CLI Login
          command: |
            az login \
          --service-principal \
          --tenant $AZURE_SP_TENANT \
          -u $AZURE_SP \
          -p $AZURE_SP_PASSWORD
      - run:
          name: terraform init
          command: | 
            terraform init
          environment:
            TF_VAR_tenancy_ocid: $TENANCY_OCID
            TF_VAR_user_ocid: $OCI_USER_ID
            TF_VAR_private_key: $OCI_PRIVATE_KEY
            TF_VAR_fingerprint: $OCI_FINGERPRINT

