version: 2.1

workflows:
  test-env-vars:
    jobs:
      - tf

jobs:
  tf:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init and plan
          command: | 
            export TF_HTTP_ADDRESS=$BACKEND_HTTP
            export TF_HTTP_UPDATE_METHOD=$BACKEND_METHOD
            terraform init
          environment:
            TF_VAR_tenancy_ocid: $TENANCY_OCID
            TF_VAR_user_ocid: $OCI_USER_ID
            TF_VAR_private_key: $OCI_PRIVATE_KEY
            TF_VAR_fingerprint: $OCI_FINGERPRINT

